export const IGDB_ENDPOINTS = {
	ageRatings: "age_ratings",
	ageRatingCategories: "age_rating_categories",
	ageRatingContentDescriptions: "age_rating_content_descriptions",
	ageRatingContentDescriptionTypes: "age_rating_content_description_types",
	ageRatingContentDescriptionsV2: "age_rating_content_descriptions_v2",
	ageRatingOrganizations: "age_rating_organizations",
	alternativeNames: "alternative_names",
	artworks: "artworks",
	artworkTypes: "artwork_types",
	characters: "characters",
	characterGenders: "character_genders",
	characterMugShots: "character_mug_shots",
	characterSpecies: "character_species",
	collections: "collections",
	collectionMemberships: "collection_memberships",
	collectionMembershipTypes: "collection_membership_types",
	collectionRelations: "collection_relations",
	collectionRelationTypes: "collection_relation_types",
	collectionTypes: "collection_types",
	companies: "companies",
	companyLogos: "company_logos",
	companySizes: "company_sizes",
	companyStatuses: "company_statuses",
	companyTypes: "company_types",
	companyTypeHistories: "company_type_histories",
	companyWebsites: "company_websites",
	covers: "covers",
	dateFormats: "date_formats",
	entityTypes: "entity_types",
	events: "events",
	eventLogos: "event_logos",
	eventNetworks: "event_networks",
	externalGames: "external_games",
	externalGameSources: "external_game_sources",
	franchises: "franchises",
	games: "games",
	gameEngines: "game_engines",
	gameEngineLogos: "game_engine_logos",
	gameLocalizations: "game_localizations",
	gameModes: "game_modes",
	gameReleaseFormats: "game_release_formats",
	gameStatuses: "game_statuses",
	gameTimeToBeats: "game_time_to_beats",
	gameTypes: "game_types",
	gameVersions: "game_versions",
	gameVersionFeatures: "game_version_features",
	gameVersionFeatureValues: "game_version_feature_values",
	gameVideos: "game_videos",
	genres: "genres",
	involvedCompanies: "involved_companies",
	keywords: "keywords",
	languages: "languages",
	languageSupports: "language_supports",
	languageSupportTypes: "language_support_types",
	multiplayerModes: "multiplayer_modes",
	networkTypes: "network_types",
	platforms: "platforms",
	platformFamilies: "platform_families",
	platformLogos: "platform_logos",
	platformTypes: "platform_types",
	platformVersions: "platform_versions",
	platformVersionCompanies: "platform_version_companies",
	platformVersionReleaseDates: "platform_version_release_dates",
	platformWebsites: "platform_websites",
	playerPerspectives: "player_perspectives",
	popularityPrimitives: "popularity_primitives",
	popularityTypes: "popularity_types",
	regions: "regions",
	releaseDates: "release_dates",
	releaseDateRegions: "release_date_regions",
	releaseDateStatuses: "release_date_statuses",
	reports: "reports",
	reportTypes: "report_types",
	screenshots: "screenshots",
	search: "search",
	themes: "themes",
	websites: "websites",
	websiteTypes: "website_types",
} as const;

export type IGDBEndpointKey = keyof typeof IGDB_ENDPOINTS;
export type IGDBEndpointPath = (typeof IGDB_ENDPOINTS)[IGDBEndpointKey];

export const IGDB_SEARCHABLE_ENDPOINTS = [
	"characters",
	"collections",
	"games",
	"platforms",
	"search",
	"themes",
] as const satisfies readonly IGDBEndpointPath[];

export type IGDBSearchableEndpointPath =
	(typeof IGDB_SEARCHABLE_ENDPOINTS)[number];
