// Default fields for different IGDB endpoints
export const defaultFields = {
	games: [
		"*",
		"screenshots.*",
		"cover.*",
		"rating",
		"release_dates.*",
		"aggregated_rating",
		"platforms.*",
		"platforms.websites.*",
		"bundles.*",
		"involved_companies.*",
		"involved_companies.company.*",
		"game_engines.*",
		"websites.*",
		"videos.*",
		"genres.*",
		"similar_games.*",
		"similar_games.screenshots.*",
		"similar_games.cover.*",
		"similar_games.genres.*",
		"similar_games.release_dates.*",
		"similar_games.platforms.*",
		"artworks.*",
	],
	genres: ["id", "name", "slug", "url"],
	companies: [
		"id",
		"name",
		"description",
		"country",
		"logo.*",
		"websites.*",
		"developed.*",
		"published.*",
	],
	themes: ["id", "name", "slug", "url"],
	game_modes: ["id", "name", "slug", "url"],
	platforms: [
		"id",
		"name",
		"abbreviation",
		"alternative_name",
		"category",
		"generation",
		"platform_logo.*",
		"websites.*",
	],
	characters: ["id", "name", "description", "games.*", "mug_shot.*", "akas"],
	collections: ["id", "name", "games.*", "url"],
	franchises: ["id", "name", "games.*", "url"],
	artworks: ["id", "image_id", "url", "width", "height", "game.*"],
	covers: ["id", "image_id", "url", "width", "height", "game.*"],
	screenshots: ["id", "image_id", "url", "width", "height", "game.*"],
} as const;

// Rate limiting constants
export const RATE_LIMIT = {
	MAX_REQUESTS_PER_SECOND: 4,
	MAX_LIMIT_PER_REQUEST: 500,
	MAX_OFFSET: 10000,
} as const;
